var express=require('express')
var fs=require('fs')
var router=express.Router();
router.get('/homeController.js',function(req,res){
    fs.readFile('src/js/controllers/homeController.js','utf8',function(err,data){
        res.send(data)
    })
})
router.get('/productsController.js',function(req,res){
    fs.readFile('src/js/controllers/productsController.js','utf8',function(err,data){
        res.send(data)
    })
})
router.get('/shapeController.js',function(req,res){
    fs.readFile('src/js/controllers/shapeController.js','utf8',function(err,data){
        res.send(data)
    })
})
router.get('/kitchenController.js',function(req,res){
    fs.readFile('src/js/controllers/kitchenController.js','utf8',function(err,data){
        res.send(data)
    })
})
router.get('/wordrobesController.js',function(req,res){
    fs.readFile('src/js/controllers/wordrobesController.js','utf8',function(err,data){
        res.send(data)
    })
})
router.get('/bedController.js',function(req,res){
    fs.readFile('src/js/controllers/bedController.js','utf8',function(err,data){
        res.send(data)
    })
})
router.get('/fulllInteriorsController.js',function(req,res){
    fs.readFile('src/js/controllers/fulllInteriorsController.js','utf8',function(err,data){
        res.send(data)
    })
})
router.get('/registerController.js',function(req,res){
    fs.readFile('src/js/controllers/registerController.js','utf8',function(err,data){
        res.send(data)
    })
})
router.get('/finalController.js',function(req,res){
    fs.readFile('src/js/controllers/finalController.js','utf8',function(err,data){
        res.send(data)
    })
})
router.get('/dataService.js',function(req,res){
    fs.readFile('src/js/dataService.js','utf8',function(err,data){
        res.send(data)
    })
})
module.exports=router;
