angular.module('app',['ui.router']).config(config)
function config($stateProvider,$urlRouterProvider){
    $stateProvider.state({
        name:'home',
        url:'/home',
        views:{
            'main':{
                templateUrl:'http://localhost:100/templates/home.html',
                controller:'homeController'
            }
        }
    })
    .state({
        name:'products',
        url:'/products',
        views:{
            'main':{
                templateUrl:'http://localhost:100/templates/products.html',
                controller:'productsController'
            }
        }
    })
    .state({
        name:'shapes',
        url:'/shapes',
        views:{
            'main':{
                templateUrl:'http://localhost:100/templates/shapes.html',
                controller:'shapeController'
            }
        }
    })
    .state({
        name:'LShape',
        url:'/LShape',
        views:{
            'main':{
                templateUrl:'http://localhost:100/templates/lshape.html',
                controller:'sizeController'
            }
        }
    })
    .state({
        name:'UShape',
        url:'/UShape',
        views:{
            'main':{
                templateUrl:'http://localhost:100/templates/UShape.html',
                controller:'sizeController'
            }
        }
    })
    .state({
        name:'parallelShape', 
        url:'/parallelShape',
        views:{
            'main':{
                templateUrl:'http://localhost:100/templates/parallelShape.html',
                controller:'sizeController'
            }
        }
    })
    .state({
        name:'straightShape',
        url:'/straightShape',
        views:{
            'main':{
                templateUrl:'http://localhost:100/templates/straightShape.html',
                controller:'sizeController'
            }
        }
    })
    .state({
        name:'register',
        url:'/register',
        views:{
            'main':{
                templateUrl:'http://localhost:100/templates/register.html',
                controller:'registerController'
            }
        }
    })
    .state({
        name:'final',
        url:'/final',
        views:{
            'main':{
                templateUrl:'http://localhost:100/templates/final.html',
                controller:'finalController'
            }
        }
    })
    $urlRouterProvider.otherwise('/home')
}
config.$inject=['$stateProvider','$urlRouterProvider']
